Description: This template deploys a VPC, subnets, NAT Gateway, and the required EC2 instances.

Parameters:
  EnvironmentName:
    Description: Environment name that will get prefixed to resource names
    Type: String

  VpcCIDR:
    Description: Please enter the CIDR for this VPC
    Type: String
    Default: 192.168.0.0/16

  VpcPublicSubnet1CIDR:
    Description: Please enter the CIDR for this subnet
    Type: String
    Default: 192.168.1.0/24

Resources:
  VPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostName: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
