Parameters:
  EC2InstanceType:
    Description: 'EC2 instance type'
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.nano
    ConstraintDescription: 'Must be a valid EC2 instance type.'

  KeyPairName:
    Description: 'Key pair name.'
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: 'Must be an existing key pair'

Mappings:
  RegionMap:
    ap-southeast-1:
      AMI: ami-091a58610910a87a9
    us-east-1:
      AMI: ami-08a52ddb321b32a8c
    ap-northeast-2:
      AMI: ami-0f2ce0bfb34039f29

Resources:
  MyEc2InstanceCf:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref TestSg
      KeyName: !Ref KeyPairName
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI

  TestSg:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable SSH via port 22'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
