Resources:
  MyEc2InstanceCf:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref TestSg
        - AmazonLinux2-sg
      KeyName: EC2Demo # key pair name
      ImageId: ami-08a52ddb321b32a8c
  TestSg:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Enable SSH via port 22'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
